[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lang = { path = "../lang" }
ariadne = "0.1.5"
clap = "3.1.6"
camino = "1.0.7"
internment = "0.6.0"
