[package]
name = "cli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lang = { path = "../lang" }
exitcode = "1.1.2"
ariadne = "0.1.3"
clap = "2.33.3"