[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lang = { path = "../lang" }
ariadne = "0.1.3"
clap = "3.0.0-beta.5"
camino = "1.0.5"
internment = "0.5.4"